# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
os:
  - linux
#  - osx
sudo: false
cache: packages
r_packages:
  - goodpractice
  - pkgdown

after_success:
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'covr::codecov()'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    r: release
