language: r
r:
  - oldrel
  - devel
  - release
os:
  - linux
env:
  global:
    - _R_CHECK_LENGTH_1_CONDITION_=verbose
    - _R_CHECK_LENGTH_1_LOGIC2_=verbose
matrix:
  include:
    - r: release
      os: osx
      brew_packages:
        - libgit2
        - imagemagick@6
cache: packages
addons:
  apt:
    sources:
    - sourceline: 'ppa:cran/imagemagick'
    packages:
    - libmagick++-dev
    - libglu1-mesa-dev
r_packages:
  - covr
  - devtools
  - photobiologyInOut
after_success:
  - Rscript -e 'covr::codecov()'
