language: R
r:
  - oldrel
  - devel
  - release
os:
  - linux
env:
  global:
    - _R_CHECK_LENGTH_1_CONDITION_=verbose
    - _R_CHECK_LENGTH_1_LOGIC2_=verbose
matrix:
  include:
    - r: release
      os: osx
      brew_packages: libgit2
sudo: false
cache: packages
addons:
  apt:
    sources:
    - sourceline: 'ppa:cran/imagemagick'
    packages:
    - libgmp3-dev
    - libmagick++-dev
    - libglu1-mesa-dev
r_packages:
  - covr
  - devtools
  - goodpractice
  - pkgdown
r_github_packages:
  - metrumresearchgroup/covrpage
after_success:
  - Rscript -e 'goodpractice::gp()'
  - Rscript -e 'covr::codecov()'
