on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04,   r: 'devel'}
          - {os: ubuntu-20.04,   r: 'release'}
          - {os: ubuntu-20.04,   r: 'release', lang: fr_FR.UTF-8}
          - {os: ubuntu-20.04,   r: 'release', tz: EST}
          - {os: ubuntu-20.04,   r: '4.0'}
          - {os: ubuntu-20.04,   r: '3.6'}
          - {os: ubuntu-20.04,   r: '3.5'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      LANG: ${{ matrix.config.lang }}
      LC_ALL: ${{ matrix.config.lang }}
      TZ: ${{ matrix.config.tz }}
      _R_CHECK_FORCE_SUGGESTS_: false
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install lang package
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install locales language-pack-fr

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rcmdcheck
            photobiologyInOut

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
