# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: macos-14,       r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-20.04,   r: 'devel'}
          - {os: ubuntu-20.04,   r: 'release'}
          - {os: ubuntu-20.04,   r: 'release', lang: fr_FR.UTF-8}
          - {os: ubuntu-20.04,   r: 'release', tz: EST}
          - {os: ubuntu-20.04,   r: '4.0'}
          - {os: ubuntu-20.04,   r: '3.6'}
          - {os: ubuntu-20.04,   r: '3.5'}

    env:
      LANG: ${{ matrix.config.lang }}
      LC_ALL: ${{ matrix.config.lang }}
      TZ: ${{ matrix.config.tz }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Install lang package
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install locales language-pack-fr

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:
            rcmdcheck
            photobiologyInOut=?ignore-before-r=3.6.0

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
